/**
 * Downloads the app's two typefaces into `public/fonts/` and writes
 * `src/styles/fonts.css` to point at them.
 *
 * Haunt Ranker is a local-first desktop app: it must look right on a machine
 * that has never been online, and Settings → About promises that nothing
 * leaves the app unless the user opens a link themselves. A stylesheet
 * fetched from Google on every launch broke both, so the fonts are shipped
 * with the application instead.
 *
 * Both families are licensed under the SIL Open Font License 1.1, which
 * permits redistribution — Inter (Rasmus Andersson) and Fraunces (Undercase
 * Type). Latin subsets only; the app's text is English.
 *
 * Run it again to pick up new font versions:
 *   node scripts/fetch-fonts.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = join(ROOT, "public", "fonts");
const STYLESHEET = join(ROOT, "src", "styles", "fonts.css");

// Chrome's UA, so Google serves woff2 rather than a legacy format.
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) " +
  "Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  {
    name: "Inter",
    slug: "inter",
    url: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap",
  },
  {
    name: "Fraunces",
    slug: "fraunces",
    url: "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&display=swap",
  },
];

/** Only the subsets an English-language app actually renders. */
const WANTED_SUBSETS = new Set(["latin", "latin-ext"]);

async function fetchText(url) {
  const response = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!response.ok) {
    throw new Error(`${url} responded ${response.status}`);
  }
  return response.text();
}

/** Google's CSS labels each @font-face block with a `/* subset *\/` comment above it. */
function parseFaces(css) {
  const faces = [];
  const pattern = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;

  for (const [, subset, body] of css.matchAll(pattern)) {
    if (!WANTED_SUBSETS.has(subset)) {
      continue;
    }
    const value = (property) => body.match(new RegExp(`${property}:\\s*([^;]+);`))?.[1].trim();
    const source = body.match(/src:\s*url\(([^)]+)\)/)?.[1];
    if (!source) {
      continue;
    }
    faces.push({
      subset,
      style: value("font-style") ?? "normal",
      weight: value("font-weight") ?? "400",
      stretch: value("font-stretch"),
      variationSettings: value("font-variation-settings"),
      unicodeRange: value("unicode-range"),
      source,
    });
  }

  return faces;
}

/**
 * Both families are variable fonts, so Google serves the *same* file for every
 * weight of a subset. Naming those by subset alone means the file ships once
 * instead of four times.
 */
function fileNameFor(family, face, sharedSources) {
  const weight = face.weight.replace(/\s+/g, "-");
  return sharedSources.has(face.source)
    ? `${family.slug}-${face.subset}.woff2`
    : `${family.slug}-${weight}-${face.subset}.woff2`;
}

async function run() {
  mkdirSync(FONT_DIR, { recursive: true });

  const blocks = [
    "/*",
    " * Self-hosted so the app works offline and makes no network request of",
    " * its own. Generated by scripts/fetch-fonts.mjs — edit that, not this.",
    " *",
    " * Inter and Fraunces are both SIL Open Font License 1.1, which permits",
    " * bundling them with an application.",
    " */",
    "",
  ];

  for (const family of FAMILIES) {
    const faces = parseFaces(await fetchText(family.url));
    if (faces.length === 0) {
      throw new Error(`No usable @font-face rules found for ${family.name}`);
    }

    const seen = new Map();
    for (const face of faces) {
      seen.set(face.source, (seen.get(face.source) ?? 0) + 1);
    }
    const sharedSources = new Set([...seen].filter(([, count]) => count > 1).map(([url]) => url));
    const downloaded = new Set();

    for (const face of faces) {
      const fileName = fileNameFor(family, face, sharedSources);
      if (!downloaded.has(fileName)) {
        const response = await fetch(face.source, { headers: { "User-Agent": USER_AGENT } });
        if (!response.ok) {
          throw new Error(`${face.source} responded ${response.status}`);
        }
        writeFileSync(join(FONT_DIR, fileName), Buffer.from(await response.arrayBuffer()));
        downloaded.add(fileName);
      }

      const declarations = [
        `  font-family: "${family.name}";`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        face.stretch ? `  font-stretch: ${face.stretch};` : null,
        face.variationSettings ? `  font-variation-settings: ${face.variationSettings};` : null,
        "  font-display: swap;",
        `  src: url("/fonts/${fileName}") format("woff2");`,
        face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : null,
      ].filter(Boolean);

      blocks.push("@font-face {", ...declarations, "}", "");
      console.log(`${family.name} ${face.weight} (${face.subset}) → public/fonts/${fileName}`);
    }
  }

  writeFileSync(STYLESHEET, `${blocks.join("\n").trimEnd()}\n`);
  console.log(`\nWrote ${STYLESHEET}`);
}

await run();
